export const browserCoreExamples = [
  "vikiclow browser status",
  "vikiclow browser start",
  "vikiclow browser stop",
  "vikiclow browser tabs",
  "vikiclow browser open https://example.com",
  "vikiclow browser focus abcd1234",
  "vikiclow browser close abcd1234",
  "vikiclow browser screenshot",
  "vikiclow browser screenshot --full-page",
  "vikiclow browser screenshot --ref 12",
  "vikiclow browser snapshot",
  "vikiclow browser snapshot --format aria --limit 200",
  "vikiclow browser snapshot --efficient",
  "vikiclow browser snapshot --labels",
];

export const browserActionExamples = [
  "vikiclow browser navigate https://example.com",
  "vikiclow browser resize 1280 720",
  "vikiclow browser click 12 --double",
  'vikiclow browser type 23 "hello" --submit',
  "vikiclow browser press Enter",
  "vikiclow browser hover 44",
  "vikiclow browser drag 10 11",
  "vikiclow browser select 9 OptionA OptionB",
  "vikiclow browser upload /tmp/vikiclow/uploads/file.pdf",
  'vikiclow browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "vikiclow browser dialog --accept",
  'vikiclow browser wait --text "Done"',
  "vikiclow browser evaluate --fn '(el) => el.textContent' --ref 7",
  "vikiclow browser console --level error",
  "vikiclow browser pdf",
];
