export const DEFAULT_VIKICLOW_BROWSER_ENABLED = true;
export const DEFAULT_BROWSER_EVALUATE_ENABLED = true;
export const DEFAULT_VIKICLOW_BROWSER_COLOR = "#11847E";
export const DEFAULT_VIKICLOW_BROWSER_PROFILE_NAME = "vikiclow";
export const DEFAULT_BROWSER_DEFAULT_PROFILE_NAME = "vikiclow";
export const DEFAULT_AI_SNAPSHOT_MAX_CHARS = 80_000;
export const DEFAULT_AI_SNAPSHOT_EFFICIENT_MAX_CHARS = 10_000;
export const DEFAULT_AI_SNAPSHOT_EFFICIENT_DEPTH = 6;
